@extends('layouts.master')
@section('title','Terms of Use')
@section('pagebody')

<!-- Start Inner Contents -->       
        
    <section class="myaccount-header">
    <div class="container">
    <h1>AIM Terms of Use</h1>
    </div>
</section>

  <section class="myaccount-body">
    <div class="myaccount-document"> 
    <div class="container">
                    <div style="font-size: small;">
<p>Effective date: May 20, 2013</p>
<p>Welcome to AIM. Please read on to learn the rules and restrictions that govern your use of our website(s), products, services and applications (the &#8220;Services&#8221;).</p>
<p>These Terms of Use (the &#8220;Terms&#8221;) are a binding contract between you and AIM, LLC. (&#8220;AIM,&#8221; &#8220;we&#8221; and &#8220;us&#8221;). You must agree to and accept all of the Terms, or you don&#8217;t have the right to use the Services. Your using the Services in any way means that you agree to all of these Terms, and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document, as well as those in the <a href="http://www.africainnovationmarket.org/privacy-policy/">AIM Privacy Policy</a>, <a href="http://members.founderdating.com/conduct">AIM Community Code of Conduct</a> and <a href="http://members.founderdating.com/copyright">Copyright Dispute Policy</a> don&#8217;t fret, it seems like a lot of material but we&#8217;ve tried our best to make these easier to read and understand for all you non-lawyers.</p>
<p><strong>Will these Terms ever change?</strong></p>
<p>We are constantly trying to improve our Services and incorporate feedback, so these Terms may need to change along with the Services. We reserve the right to change the Terms at any time, but if we do, we will bring it to your attention by placing a notice on the www.AIM.com website and/or by sending you an email.</p>
<p>If you don&#8217;t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to any and all of the changes.</p>
<p>Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.</p>
<p><strong>What about my privacy?</strong></p>
<p>AIM takes the privacy of its users very seriously. Please refer the current AIM Privacy Policy.</p>
<p>We do not knowingly collect or solicit personally identifiable information from children under 13; if you are a child under 13, please do not attempt to register for the Services or send any personal information about yourself to us. If we learn we have collected personal information from a child under 13, we will delete that information as quickly as possible. If you believe that a child under 13 may have provided us personal information, please contact us at <span style="text-decoration: underline;">contact@AIM.com</span></p>
<p><strong>What are the basics of using AIM?</strong></p>
<p>In order to access and use AIM Services, you must complete our application and be accepted by us (if accepted, a &#8220;Member&#8221;) and pay all applicable fees.</p>
<p>To apply for membership, you must sign in using your verified third-party account credentials (for example, your LinkedIn, Facebook, Twitter, or email and password -note that AIM <em>does not</em> see or store these credentials). You may not submit third-party account credentials that belong to another person. You represent and warrant that all information you provide us, including all information contained in your LinkedIn, Facebook, Twitter profile or email, is accurate, complete, and updated. If your verified third-party account contains falsified information and/or is otherwise misleading or inaccurate, you may (in our sole discretion) be banned from the Services and your application or membership may be terminated immediately. As part of the application process, you will be required to submit vouches for your credentials (&#8220;References&#8221;). We may contact the References you provide us to help us assess your application. References do not have to register with AIM in order to vouch for an applicant, but we ask that References sign in using certain verified third-party account credentials (for example, LinkedIn sign-in information) so that we may verify who they are. We do not see or store References&#8217; third-party account credentials, but we may be able to view certain information contained in their third-party account (for example, if they sign in with their LinkedIn credentials we may be able to view their LinkedIn connections).</p>
<p>You represent and warrant that you are of legal age to form a binding contract (or if not, you&#8217;ve received your parent&#8217;s or guardian&#8217;s permission to use the Services and gotten your parent or guardian to agree to these Terms on your behalf).</p>
<p>As a Member of the Services, you will not transfer your AIM account to anyone else without our prior written permission. You are responsible for maintaining the security and confidentiality of your account credentials and for all activities that occur in your account.</p>
<p>You will only use the Services for your personal, internal business use, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws, then you aren&#8217;t authorized to use the Services. We can&#8217;t and won&#8217;t be responsible for your using the Services in a way that breaks the law.</p>
<p><strong>Your use of the Services is subject to the following additional restrictions:</strong></p>
<p>You represent, warrant, and agree that you will not contribute any Content or User Submission (each of those terms is defined below) or otherwise use the Services or interact with the Services in a manner that:</p>
<p>Infringes or violates the intellectual property rights or any other rights of anyone else (including AIM);</p>
<p>Violates any law or regulation;</p>
<p>Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;</p>
<p>Expresses or implies that any statements made by you are endorsed by AIM without obtaining our specific prior written consent;</p>
<p>Removes any copyright trademark or other proprietary rights notices contained in the Services;</p>
<p>Interferes with or disrupts the Services or the site, servers or networks connected to the Services or the site;</p>
<p>&#8220;Frames&#8221; or &#8220;mirrors&#8221; any part of the Services without AIM&#8217;s prior written consent`;</p>
<p>Jeopardizes the security of your AIM account or anyone else&#8217;s (such as allowing someone else to log on as you on the Services);</p>
<p>Attempts, in any manner, to obtain the password, account, or other security information from any other user;</p>
<p>Violates the security of any computer network, or cracks any passwords or security encryption codes;</p>
<p>Runs Maillist, Listserv, any form of auto-responder or &#8220;spam&#8221; on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services&#8217; infrastructure);</p>
<p>&#8220;Crawls,&#8221; &#8220;scrapes,&#8221; or &#8220;spiders&#8221; any page or portion of the Services (through use of manual or automated means);</p>
<p>Copies or stores any significant portion of the Content;</p>
<p>Decompiles, reverse engineers, or otherwise attempts to obtain the source code of the Services;</p>
<p>Is a solicitation or advertisement (including, without limitation, solicitations or advertisements for the purchase or sale of any products or services, attendance to social and/or networking functions for commercial purposes, and offers of or requests for employment);</p>
<p>Attempts to recruit other Members as your employees;</p>
<p>Uses the public discussion forum part of the Services to advertise your product/idea or need for a cofounder.</p>
<p>In your public account profile or discussion areas, you will not provide the following types of information: telephone numbers, street addresses, last names, URLs, and/or email addresses. If you provide any of this information, you do so at your own risk and we assume no responsibility for the use of such information.</p>
<p>A violation of any of the foregoing is grounds for termination of your right to use or access the Services without any warning.</p>
<p><strong>What are my rights in the Services?</strong></p>
<p>The materials displayed or performed on the Services, including, but not limited to, text, graphics, articles, photos, images, illustrations, User Submissions, and so forth (all of the foregoing, the &#8220;Content&#8221;) are protected by copyright and other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won&#8217;t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else&#8217;s (including AIM&#8217;s) rights.</p>
<p>You understand that AIM owns the Services. You won&#8217;t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), creative derivative works based on, or otherwise exploit any of the Services.</p>
<p>The Services may allow you to copy or download certain Content; please remember that just because this functionality exists, doesn&#8217;t mean that all the restrictions above don&#8217;t apply.</p>
<p><strong>Do I have to grant any rights to AIM or to other users</strong>?</p>
<p>Anything you post, upload, share, store, or otherwise provide through the Services is your &#8220;User Submission.&#8221; Some User Submissions are viewable by other users. In order to display your User Submissions on the Services, and to allow other users to enjoy them (where applicable), you grant us certain rights in those User Submissions. Please note that all of the following licenses (ie, rights that you grant) are subject to our AIM Privacy Policy to the extent they relate to User Submissions that are also your personally-identifiable information.</p>
<p>For all User Submissions, you hereby grant AIM a license to translate, modify (for technical purposes, for example making sure your content is viewable on your iPhone, iPad as well as your computer) and reproduce such User Submissions, in each case to enable us to operate the Services, as described in more detail below. This is a license only &#8211; your ownership in User Submissions is not affected.</p>
<p>If you share a User Submission publicly on the Services and/or in a manner that more than just you or certain specified users can view (a &#8220;Public User Submission&#8221;), then you grant AIM the license above, as well as a license to display, perform, and distribute your Public User Submission for the purpose of displaying that Public User Submission to all AIM users and providing you the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission in connection with AIM and the Services. Also, you grant all other users of the Services a license to access that Public User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.</p>
<p>You agree that the licenses you grant are royalty-free, irrevocable, and worldwide, for as long as your User Submissions are stored with us.</p>
<p>Finally, you understand and agree that AIM, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media.</p>
<p><strong>What if I see something on the Services that infringes my copyright</strong>?</p>
<p>You may have heard of the Digital Millennium Copyright Act (the &#8220;DMCA&#8221;), as it relates to online service providers, like AIM, being asked to remove material that allegedly violates someone&#8217;s copyright. We respect others&#8217; intellectual property rights, and we reserve the right to delete or disable Content alleged to be infringing, and to terminate the accounts of repeat infringers.</p>
<p><strong>Who is responsible for what I see and do on the Services</strong>?</p>
<p>Any information or content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such content originated, and you access all such information and content at your own risk, and we aren&#8217;t liable for any errors or omissions in that information or content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can&#8217;t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services.</p>
<p>You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services.</p>
<p>The Services may contain links or connections to third party websites or services that are not owned or controlled by AIM. When you access third party websites or use third party services, you accept that there are risks in doing so, and that AIM is not responsible for such risks. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third party website or service that you visit or utilize.</p>
<p>AIM has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third party websites or by any third party that you interact with through the Services. In addition, AIM will not and cannot monitor, verify, censor or edit the content of any third party site or service. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third party website or service.</p>
<p>Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that AIM shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.</p>
<p>If there is a dispute between participants on this site, or between users and any third party, you agree that AIM is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release AIM, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services.</p>
<p><strong>Will AIM ever change the Services?</strong></p>
<p>We&#8217;re always trying to improve the Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We&#8217;ll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn&#8217;t always practical. Similarly, we reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.</p>
<p><strong>Does AIM cost anything?</strong></p>
<p>You might pay a membership fee upon accepting your membership invitation in order to become a Member. As a Member, you may be required to pay additional fees in order to access additional features and services, such as premium services and investment interests. AIM reserves the right to charge for certain or all Services presently offered and which may be offered in the future. We will notify you before any Services you are then currently using begins to charge a fee. If you wish to continue using such Services, you must pay all applicable fees for such Services.</p>
<p>AIM will bill you through an online account located in your account settings. You must provide an approved method of payment and you hereby authorize AIM to charge your payment method for all applicable fees.</p>
<p><strong>What if I want to stop using AIM</strong> <strong>? </strong></p>
<p>You&#8217;re free to do that at any time, by going into your account settings page and suspending or canceling your AIM account; please refer to our Privacy Policy as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services.</p>
<p>AIM is also free to terminate (or suspend access to) your use of the Services or your account, for any reason in our discretion, including your breach of these Terms. AIM has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.</p>
<p>Account termination may result in destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account. Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us.</p>
<p><strong>What else do I need to know?</strong></p>
<p><em>Warranty Disclaimer.</em> AIM does not make any representations or warranties concerning any content contained in or accessing through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, legality, reliability, or decency of material contained in or accessed through the Services. We make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services, including without limitation, opinions, advice, statements, offers, and/or other information or content made available on the Services that do not originate from AIM. We do not guarantee the completeness or usefulness of any information offered on the Services nor do we adopt, endorse, or accept responsibility for any content provided by other users on the Services. Products and services purchased or offered (whether or not following such recommendations and suggestions) through the Services are provided &#8220;AS IS&#8221; and without any warranty of any kind from AIM or others (unless, with respect to such others only, provided expressly and unambiguously in writing by a designated third party for a specific product). THE SERVICES AND CONTENT ARE PROVIDED ON AN &#8220;AS-IS&#8221; BASIS, WITHOUT WARRANTIES OR ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. SOME STATES AN COUNTRIES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
<p><em>Limitation of Liability</em> . TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL AIM BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, OR (B) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) $100 OR (II) THE AMOUNTS PAID BY YOU TO AIM IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM, OR (III) ANY MATTER BEYOND OUR REASONABLE CONTROL. SOME STATES AND COUNTRIES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
<p><em>Indemnity</em> . You agree to indemnify and hold AIM, its affiliates, officers, agents, employees, and partners harmless for and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys&#8217; fees) arising from or in any way related to any third party claims relating to (a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of these Terms. In the event of such a claim, suit, or action (&#8220;Claim&#8221;), we will provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder).</p>
<p><em>Assignment</em> . You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without AIM&#8217;s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.</p>
<p><em>Choice of Law; Arbitration</em> . These Terms are governed by and will be construed under the laws of the District of Columbia, without regard to the conflicts of laws provisions thereof. Any dispute arising from or relating to the subject matter of these Terms shall be finally settled in Washington, DC, accordance with the Streamlined Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, Inc. (&#8220;JAMS&#8221;) then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of JAMS arbitrators in accordance with the Arbitration Rules and Procedures of JAMS. Judgment upon the award rendered by such arbitrator may be entered in any court of competent jurisdiction. Notwithstanding the foregoing obligation to arbitrate disputes, each party shall have the right to pursue injunctive or other equitable relief at any time, from any court of competent jurisdiction. For all purposes of this Agreement, the parties consent to exclusive jurisdiction and venue in the District or federal courts located in.</p>
<p><em>Miscellaneous</em> . You will be responsible for withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and AIM agree that these Terms are the complete and exclusive statement of the mutual understanding between you and AIM, and that it supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms, and that all modifications to these Terms must be in a writing signed by both parties (except as otherwise provided herein). No agency, partnership, joint venture, or employment is created as a result of these Terms and you do not have any authority of any kind to bind AIM in any respect whatsoever. You and AIM agree there are no third party beneficiaries intended under this Agreement.</p>
<p>&nbsp;</p>
<p>&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8211;</p>
<p>NOTICES FROM AIM</p>
<p>If AIM needs to contact you about your product or account, you consent to receive the notices by email. You agree that any such notices that we send you electronically will satisfy any legal communication requirements.</p>
</div>
<!-- AddThis Sharing Buttons below -->                  </div>
      </div>
    </section>

@endsection